@startuml Class_FastAPI



  class Alliance {
    + id_alliance : int
    + nom : str
    + tag : str
    + description : str
    --
    + membres : List[CompteJeu]
    + configurations : List[ConfigurationDefense]
  }

  class Utilisateur {
    + id_utilisateur : int
    + discord_id : str
    + discord_username : str
    + email : str
    + role : UserRole
    --
    + comptes_jeu : List[CompteJeu]
  }

  class CompteJeu {
    + id_compte_jeu : int
    + utilisateur_id : int
    + alliance_id : int
    + pseudo_jeu : str
    + est_principal : bool
    --
    + utilisateur : Utilisateur
    + alliance : Alliance
    + roster : List[ChampionUtilisateur]
    + placements_responsables : List[PlacementDefense]
  }

  class Champion {
    + id_champion : int
    + nom : str
    + classe : ChampionClass
    + image_url : str
    --
    + instances : List[ChampionUtilisateur]
  }

  class ChampionUtilisateur {
    + id_champion_utilisateur : int
    + compte_jeu_id : int
    + champion_id : int
    + etoiles : int
    + rang : int
    + niveau : int
    + signature : int
    + prestige : int
    + est_favori : bool
    --
    + compte_jeu : CompteJeu
    + champion : Champion
    + placements : List[PlacementDefense]
  }

  class ConfigurationDefense {
    + id_config : int
    + alliance_id : int
    + nom : str
    + type : DefenseType
    + est_active : bool
    --
    + alliance : Alliance
    + noeuds : List[Noeud]
  }

  class Noeud {
    + id_noeud : int
    + config_id : int
    + numero : str
    + description_buffs : str
    --
    + configuration : ConfigurationDefense
    + placements : List[PlacementDefense]
  }

  class PlacementDefense {
    + id_placement : int
    + noeud_id : int
    + champion_utilisateur_id : int
    + compte_jeu_responsable_id : int
    + ordre : int
    + statut : PlacementStatus
    + notes_strategie : str
    --
    + noeud : Noeud
    + champion_utilisateur : ChampionUtilisateur
    + responsable : CompteJeu
  }


Utilisateur "1" *-- "N" CompteJeu
Alliance "1" *-- "N" CompteJeu
CompteJeu "1" *-- "N" ChampionUtilisateur
Champion "1" *-- "N" ChampionUtilisateur
ConfigurationDefense "1" *-- "N" Noeud
Noeud "1" *-- "N" PlacementDefense
ChampionUtilisateur "1" *-- "N" PlacementDefense
CompteJeu "1" --> "N" PlacementDefense : responsable

@enduml