"""Regenerate docs/mld.puml from the SQLModel metadata: `make mld` from api/."""

from pathlib import Path

from sqlalchemy.dialects import mysql

from src.models import SQLModel

OUT = Path(__file__).with_name("mld.puml")


def column_line(col) -> str:
    tags = [t for t, on in (("PK", col.primary_key), ("UQ", col.unique)) if on]
    tags += [f"FK → {fk.column.table.name}.{fk.column.name}" for fk in col.foreign_keys]
    mark = "* " if col.primary_key or not col.nullable else ""
    return f"  {mark}{col.name} : {col.type.compile(dialect=mysql.dialect())}" + "".join(
        f" <<{t}>>" for t in tags
    )


def render() -> str:
    lines = [
        "@startuml MLD_MCOC",
        "' Generated by docs/gen_mld.py — do not edit by hand.",
        "left to right direction",
        "hide circle",
        "skinparam shadowing false",
        "skinparam monochrome true",
        "skinparam linetype ortho",
        "",
    ]
    relations = []
    for table in SQLModel.metadata.sorted_tables:
        pk = [c for c in table.columns if c.primary_key]
        rest = [c for c in table.columns if not c.primary_key]
        lines += [
            f'entity "{table.name}" as {table.name} {{',
            *map(column_line, pk),
            "  --",
            *map(column_line, rest),
            "}",
            "",
        ]
        for fk in table.foreign_keys:
            parent_side = "o|" if fk.parent.nullable else "||"
            relations.append(f"{table.name} }}o--{parent_side} {fk.column.table.name}")
    return "\n".join([*lines, *sorted(set(relations)), "", "@enduml", ""])


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUT} ({len(SQLModel.metadata.tables)} tables)")
