@startuml MCD_MCOC
title Modèle Conceptuel de Données - Mawster Alliance Manager
hide circle
skinparam shadowing false
skinparam monochrome true

entity "Alliance" as alliance {
  * id_alliance <<PK>>
  --
  nom
  tag
  description
}

entity "Utilisateur" as utilisateur {
  * id_utilisateur <<PK>>
  --
  discord_id
  discord_username
  email
  role
}

entity "CompteJeu" as compte_jeu {
  * id_compte_jeu <<PK>>
  --
  * utilisateur_id <<FK>>
  * alliance_id <<FK>>
  pseudo_jeu
  est_principal
}

entity "Champion" as champion {
  * id_champion <<PK>>
  --
  nom
  classe
  image_url
}

entity "ChampionUtilisateur\n(roster)" as roster {
  * id_champion_utilisateur <<PK>>
  --
  * compte_jeu_id <<FK>>
  * champion_id <<FK>>
  etoiles
  rang
  niveau
  signature
}

entity "ConfigurationDefense" as config {
  * id_config <<PK>>
  --
  * alliance_id <<FK>>
  nom
  type
  est_active
}

entity "Noeud" as noeud {
  * id_noeud <<PK>>
  --
  * config_id <<FK>>
  numero
  description_buffs
}

entity "PlacementDefense" as placement {
  * id_placement <<PK>>
  --
  * noeud_id <<FK>>
  * champion_utilisateur_id <<FK>>
  * compte_jeu_responsable_id <<FK>>
  ordre
  statut
  notes_strategie
}

utilisateur ||--o{ compte_jeu : "possède"
alliance ||--o{ compte_jeu : "contient"
compte_jeu ||--o{ roster : "a_dans_son_roster"
champion ||--o{ roster : "est_instance_de"
config ||--o{ noeud : "comprend"
noeud ||--o{ placement : "a"
roster ||--o{ placement : "est_placé_sur"
compte_jeu ||--o{ placement : "est_responsable_de"


@enduml