repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: [--fix]
        working_directory: api
      - id: ruff-format
        working_directory: api
