networks:
  internal-dev:
    driver: bridge

services:
  mariadb-dev:
    image: mariadb
    ports:
      - 3305:3306
    container_name: mariadb-dev
    networks:
      - internal-dev
    environment:
      - MARIADB_DATABASE=mawster
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=rootpassword
    volumes:
      - ./db/mawster-db:/var/lib/mysql
  phpmyadmin-dev:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    container_name: myadmin-dev
    networks:
      - internal-dev
    environment:
      - PMA_HOST=mariadb-dev
      - PMA_PORT=3306
    depends_on:
      - mariadb-dev
  mariadb-test:
    image: mariadb
    ports:
      - 3307:3306
    container_name: mariadb-test
    networks:
      - internal-dev
    environment:
      - MARIADB_DATABASE=mawster
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=rootpassword
  phpmyadmin-test:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    container_name: myadmin-test
    networks:
      - internal-dev
    environment:
      - PMA_HOST=mariadb-test
      - PMA_PORT=3306
    depends_on:
      - mariadb-test
