from sqlmodel import SQLModel  # noqa: F401

from src.models.alliance.Alliance import Alliance  # noqa: F401
from src.models.alliance.AllianceInvitation import AllianceInvitation  # noqa: F401
from src.models.alliance.AllianceOfficer import AllianceOfficer  # noqa: F401
from src.models.alliance.AllianceVisitor import AllianceVisitor  # noqa: F401
from src.models.alliance.DefensePlacement import DefensePlacement  # noqa: F401
from src.models.champion.Champion import Champion  # noqa: F401
from src.models.champion.ChampionSagaRole import ChampionSagaRole  # noqa: F401
from src.models.champion.ChampionUser import ChampionUser  # noqa: F401
from src.models.champion.RequestedUpgrade import RequestedUpgrade  # noqa: F401
from src.models.matchup.MatchupRating import MatchupRating  # noqa: F401
from src.models.matchup.MatchupSynergy import MatchupSynergy  # noqa: F401
from src.models.user.GameAccount import GameAccount  # noqa: F401
from src.models.user.GameAccountMastery import GameAccountMastery  # noqa: F401
from src.models.user.LoginLog import LoginLog  # noqa: F401
from src.models.user.Mastery import Mastery  # noqa: F401
from src.models.user.NoteReport import NoteReport  # noqa: F401
from src.models.user.User import User  # noqa: F401
from src.models.user.UserMute import UserMute  # noqa: F401
from src.models.user.UserWarn import UserWarn  # noqa: F401
from src.models.vision.VisionImport import VisionImport  # noqa: F401
from src.models.vision.VisionJob import VisionJob  # noqa: F401
from src.models.vision.VisionPrediction import VisionPrediction  # noqa: F401
from src.models.vision.VisionPredictionCandidate import VisionPredictionCandidate  # noqa: F401
from src.models.vision.VisionSample import VisionSample  # noqa: F401
from src.models.war.Season import Season  # noqa: F401
from src.models.war.War import War  # noqa: F401
from src.models.war.WarBan import WarBan  # noqa: F401
from src.models.war.WarDefensePlacement import WarDefensePlacement  # noqa: F401
from src.models.war.WarFightNote import WarFightNote  # noqa: F401
from src.models.war.WarFightNoteRevision import WarFightNoteRevision  # noqa: F401
from src.models.war.WarFightPrefight import WarFightPrefight  # noqa: F401
from src.models.war.WarFightRecord import WarFightRecord  # noqa: F401
from src.models.war.WarFightRecordImport import WarFightRecordImport  # noqa: F401
from src.models.war.WarFightSynergy import WarFightSynergy  # noqa: F401
from src.models.war.WarPrefightAttacker import WarPrefightAttacker  # noqa: F401
from src.models.war.WarSynergyAttacker import WarSynergyAttacker  # noqa: F401
