from src.models.User import User  # noqa: F401
from src.models.LoginLog import LoginLog  # noqa: F401
from src.models.GameAccount import GameAccount  # noqa: F401
from src.models.Alliance import Alliance  # noqa: F401
from src.models.Champion import Champion  # noqa: F401
from src.models.ChampionUser import ChampionUser  # noqa: F401
from src.models.AllianceOfficer import AllianceOfficer  # noqa: F401
from src.models.AllianceInvitation import AllianceInvitation  # noqa: F401
from src.models.RequestedUpgrade import RequestedUpgrade  # noqa: F401
from src.models.DefensePlacement import DefensePlacement  # noqa: F401
from src.models.War import War  # noqa: F401
from src.models.WarDefensePlacement import WarDefensePlacement  # noqa: F401
from src.models.WarSynergyAttacker import WarSynergyAttacker  # noqa: F401
from src.models.WarBan import WarBan  # noqa: F401
from src.models.WarPrefightAttacker import WarPrefightAttacker  # noqa: F401
from src.models.WarFightRecord import WarFightRecord  # noqa: F401
from src.models.WarFightSynergy import WarFightSynergy  # noqa: F401
from src.models.WarFightPrefight import WarFightPrefight  # noqa: F401
from src.models.Season import Season  # noqa: F401
from src.models.Mastery import Mastery  # noqa: F401
from src.models.GameAccountMastery import GameAccountMastery  # noqa: F401
from sqlmodel import SQLModel  # noqa: F401
