"""vision_sample_bucket_only_json

Revision ID: 06033433e335
Revises: 83a2e5379297
Create Date: 2026-07-18 12:35:33.179861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "06033433e335"
down_revision: Union[str, None] = "83a2e5379297"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vision_sample", "truth_json")
    op.drop_column("vision_sample", "pred_json")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vision_sample", sa.Column("pred_json", mysql.VARCHAR(length=255), nullable=False)
    )
    op.add_column(
        "vision_sample", sa.Column("truth_json", mysql.VARCHAR(length=255), nullable=False)
    )
    # ### end Alembic commands ###
