"""add-assists

Revision ID: 0c439ddb6a65
Revises: b24d0bf5217d
Create Date: 2026-05-17 19:56:55.724169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "0c439ddb6a65"
down_revision: Union[str, None] = "b24d0bf5217d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "war_defense_placement", sa.Column("assist_champion_user_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        None, "war_defense_placement", "champion_user", ["assist_champion_user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "war_defense_placement", type_="foreignkey")
    op.drop_column("war_defense_placement", "assist_champion_user_id")
    # ### end Alembic commands ###
