"""add_fight_completed

Revision ID: 0cc33c59d17e
Revises: b5c5e20d304c
Create Date: 2026-04-30 21:22:26.524255

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0cc33c59d17e"
down_revision: str | None = "b5c5e20d304c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "war_defense_placement", sa.Column("is_combat_completed", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("war_defense_placement", "is_combat_completed")
    # ### end Alembic commands ###
