"""init

Revision ID: 178b878847d9
Revises: 6366528b2ae2
Create Date: 2026-04-24 22:43:59.264783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "178b878847d9"
down_revision: Union[str, None] = "6366528b2ae2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alliance", sa.Column("elo", sa.Integer(), nullable=False))
    op.add_column("alliance", sa.Column("tier", sa.Integer(), nullable=False))
    op.add_column("war", sa.Column("win", sa.Boolean(), nullable=True))
    op.add_column("war", sa.Column("elo_change", sa.Integer(), nullable=True))
    op.add_column("war", sa.Column("tier", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("war", "tier")
    op.drop_column("war", "elo_change")
    op.drop_column("war", "win")
    op.drop_column("alliance", "tier")
    op.drop_column("alliance", "elo")
    # ### end Alembic commands ###
