"""war_fight_note_and_revision

Revision ID: 1a4847d6b57d
Revises: 8ab9a3f84ff8
Create Date: 2026-06-21 01:20:12.917036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "1a4847d6b57d"
down_revision: Union[str, None] = "8ab9a3f84ff8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "war_fight_note",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("war_defense_placement_id", sa.Uuid(), nullable=False),
        sa.Column("war_id", sa.Uuid(), nullable=False),
        sa.Column("alliance_id", sa.Uuid(), nullable=False),
        sa.Column("battlegroup", sa.Integer(), nullable=False),
        sa.Column("node_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_by_game_account_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_game_account_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("war_fight_record_id", sa.Uuid(), nullable=True),
        sa.Column("whitelisted_at", sa.DateTime(), nullable=True),
        sa.Column("whitelisted_by_id", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["alliance_id"],
            ["alliance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_game_account_id"],
            ["game_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_game_account_id"],
            ["game_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["war_defense_placement_id"],
            ["war_defense_placement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["war_fight_record_id"],
            ["war_fight_record.id"],
        ),
        sa.ForeignKeyConstraint(
            ["war_id"],
            ["war.id"],
        ),
        sa.ForeignKeyConstraint(
            ["whitelisted_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("war_id", "battlegroup", "node_number", name="uq_war_fight_note_node"),
    )
    op.create_table(
        "war_fight_note_revision",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("note_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("edited_by_game_account_id", sa.Uuid(), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["edited_by_game_account_id"],
            ["game_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["war_fight_note.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("war_fight_note_revision")
    op.drop_table("war_fight_note")
    # ### end Alembic commands ###
