"""add_tierlist_tables

Revision ID: 21d703c984fe
Revises: 6cb7bcca2cc1
Create Date: 2026-09-08 18:40:42.706817

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21d703c984fe"
down_revision: str | None = "6cb7bcca2cc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tierlist",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tierlist_champion_tag",
        sa.Column("champion_id", sa.Uuid(), nullable=False),
        sa.Column("tierlist_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("is_six_star_only", sa.Boolean(), nullable=False),
        sa.Column("is_attacker", sa.Boolean(), nullable=False),
        sa.Column("is_defender", sa.Boolean(), nullable=False),
        sa.Column("is_alliance_war", sa.Boolean(), nullable=False),
        sa.Column("is_battlegrounds", sa.Boolean(), nullable=False),
        sa.Column("is_awakened", sa.Boolean(), nullable=False),
        sa.Column("signature", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["champion_id"],
            ["champion.id"],
        ),
        sa.ForeignKeyConstraint(["tierlist_id"], ["tierlist.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tierlist_id", "champion_id", name="uq_tierlist_tag_champion"),
    )
    op.create_table(
        "tierlist_tier",
        sa.Column("tierlist_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tierlist_id"], ["tierlist.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tierlist_id", "position", name="uq_tierlist_tier_position"),
    )
    op.create_table(
        "tierlist_ranking",
        sa.Column("champion_id", sa.Uuid(), nullable=False),
        sa.Column("tierlist_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tier_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["champion_id"],
            ["champion.id"],
        ),
        sa.ForeignKeyConstraint(["tier_id"], ["tierlist_tier.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tierlist_id"], ["tierlist.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tierlist_id", "champion_id", name="uq_tierlist_ranking_champion"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tierlist_ranking")
    op.drop_table("tierlist_tier")
    op.drop_table("tierlist_champion_tag")
    op.drop_table("tierlist")
    # ### end Alembic commands ###
