"""add_big_thing_war

Revision ID: 26f1feb0c934
Revises: 94d7d9280a40
Create Date: 2026-06-03 12:32:33.923415

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "26f1feb0c934"
down_revision: Union[str, None] = "a08a2f9b992c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "season",
        sa.Column("format", sa.Enum("regular", "big_thing", name="seasonformat"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("season", "format")
    # ### end Alembic commands ###
