"""init

Revision ID: 27f067e9cc5a
Revises: e2baeab914ab
Create Date: 2026-04-13 09:20:32.792886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '27f067e9cc5a'
down_revision: Union[str, None] = 'e2baeab914ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('champion', sa.Column('is_saga_attacker', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('champion', sa.Column('is_saga_defender', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('champion', 'is_saga_defender')
    op.drop_column('champion', 'is_saga_attacker')
    # ### end Alembic commands ###
