"""add war and war defense placement

Revision ID: 2b66dc5bf643
Revises: ec1f9e092dd1
Create Date: 2026-03-15 23:32:47.464603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '2b66dc5bf643'
down_revision: Union[str, None] = 'ec1f9e092dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('war',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alliance_id', sa.Uuid(), nullable=False),
    sa.Column('opponent_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['game_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('war_defense_placement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('war_id', sa.Uuid(), nullable=False),
    sa.Column('battlegroup', sa.Integer(), nullable=False),
    sa.Column('node_number', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Uuid(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('ascension', sa.Integer(), nullable=False),
    sa.Column('placed_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['placed_by_id'], ['game_account.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('war_id', 'battlegroup', 'node_number', name='uq_war_defense_node')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('war_defense_placement')
    op.drop_table('war')
    # ### end Alembic commands ###
