"""add_vision_presigned_upload_fields

Revision ID: 44ec4546df6d
Revises: 2bddb8e3af0c
Create Date: 2026-07-31 19:59:56.624736

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "44ec4546df6d"
down_revision: str | None = "2bddb8e3af0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vision_import",
        "status",
        existing_type=mysql.ENUM("PENDING", "RUNNING", "DONE", "FAILED", "CONFIRMED", "CANCELLED"),
        type_=sa.Enum(
            "AWAITING_UPLOAD",
            "PENDING",
            "RUNNING",
            "DONE",
            "FAILED",
            "CONFIRMED",
            "CANCELLED",
            name="visionimportstatus",
        ),
        existing_nullable=False,
    )
    op.add_column(
        "vision_job",
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    )
    op.alter_column(
        "vision_job",
        "status",
        existing_type=mysql.ENUM("PENDING", "RUNNING", "DONE", "FAILED"),
        type_=sa.Enum(
            "AWAITING_UPLOAD", "PENDING", "RUNNING", "DONE", "FAILED", name="visionjobstatus"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vision_job",
        "status",
        existing_type=sa.Enum(
            "AWAITING_UPLOAD", "PENDING", "RUNNING", "DONE", "FAILED", name="visionjobstatus"
        ),
        type_=mysql.ENUM("PENDING", "RUNNING", "DONE", "FAILED"),
        existing_nullable=False,
    )
    op.drop_column("vision_job", "filename")
    op.alter_column(
        "vision_import",
        "status",
        existing_type=sa.Enum(
            "AWAITING_UPLOAD",
            "PENDING",
            "RUNNING",
            "DONE",
            "FAILED",
            "CONFIRMED",
            "CANCELLED",
            name="visionimportstatus",
        ),
        type_=mysql.ENUM("PENDING", "RUNNING", "DONE", "FAILED", "CONFIRMED", "CANCELLED"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
