"""war_fight_note_with_moderation

Revision ID: 491061423fd5
Revises: 8ab9a3f84ff8
Create Date: 2026-06-23 14:27:40.691174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "491061423fd5"
down_revision: Union[str, None] = "8ab9a3f84ff8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_mute",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("muted_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("lifted_at", sa.DateTime(), nullable=True),
        sa.Column("lifted_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lifted_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["muted_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_warn",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("warned_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warned_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "war_fight_note",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("war_defense_placement_id", sa.Uuid(), nullable=False),
        sa.Column("war_id", sa.Uuid(), nullable=False),
        sa.Column("alliance_id", sa.Uuid(), nullable=False),
        sa.Column("battlegroup", sa.Integer(), nullable=False),
        sa.Column("node_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_by_game_account_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_game_account_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("war_fight_record_id", sa.Uuid(), nullable=True),
        sa.Column("whitelisted_at", sa.DateTime(), nullable=True),
        sa.Column("whitelisted_by_id", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["alliance_id"],
            ["alliance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_game_account_id"],
            ["game_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_game_account_id"],
            ["game_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["war_defense_placement_id"],
            ["war_defense_placement.id"],
        ),
        sa.ForeignKeyConstraint(
            ["war_fight_record_id"],
            ["war_fight_record.id"],
        ),
        sa.ForeignKeyConstraint(
            ["war_id"],
            ["war.id"],
        ),
        sa.ForeignKeyConstraint(
            ["whitelisted_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("war_id", "battlegroup", "node_number", name="uq_war_fight_note_node"),
    )
    op.create_table(
        "note_report",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("note_id", sa.Uuid(), nullable=False),
        sa.Column("reporter_game_account_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "resolved", "dismissed", name="notereportstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_by_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["war_fight_note.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reporter_game_account_id"],
            ["game_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "note_id",
            "reporter_game_account_id",
            "status",
            name="uq_note_report_active_per_account",
        ),
    )
    op.create_table(
        "war_fight_note_revision",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("note_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("edited_by_game_account_id", sa.Uuid(), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["edited_by_game_account_id"],
            ["game_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["war_fight_note.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "season",
        "status",
        existing_type=mysql.ENUM("ended", "upcoming", "active"),
        type_=sa.Enum("upcoming", "active", "ended", name="seasonstatus"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "season",
        "status",
        existing_type=sa.Enum("upcoming", "active", "ended", name="seasonstatus"),
        type_=mysql.ENUM("ended", "upcoming", "active"),
        existing_nullable=False,
    )
    op.drop_table("war_fight_note_revision")
    op.drop_table("note_report")
    op.drop_table("war_fight_note")
    op.drop_table("user_warn")
    op.drop_table("user_mute")
    # ### end Alembic commands ###
