"""add status to war

Revision ID: 59cb9b765093
Revises: 2b66dc5bf643
Create Date: 2026-03-16 19:50:06.279314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '59cb9b765093'
down_revision: Union[str, None] = '2b66dc5bf643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'alliance', 'game_account', ['owner_id'], ['id'], use_alter=True)
    op.add_column('war', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('war', 'status')
    op.drop_constraint(None, 'alliance', type_='foreignkey')
    # ### end Alembic commands ###
