"""init

Revision ID: 5bf7d1462a3a
Revises: b119f79dc19e
Create Date: 2026-02-22 00:35:31.757681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '5bf7d1462a3a'
down_revision: Union[str, None] = 'b119f79dc19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'alliance', 'game_account', ['owner_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alliance', type_='foreignkey')
    # ### end Alembic commands ###
