"""fix_not_unique_prefights

Revision ID: 5cfbb1d36027
Revises: a305c37823c5
Create Date: 2026-04-05 04:01:04.414257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '5cfbb1d36027'
down_revision: Union[str, None] = 'a305c37823c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_war_prefight_champion'), table_name='war_prefight_attacker')
    op.create_unique_constraint('uq_war_prefight_champion_node', 'war_prefight_attacker', ['war_id', 'battlegroup', 'champion_user_id', 'target_node_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_war_prefight_champion_node', 'war_prefight_attacker', type_='unique')
    op.create_index(op.f('uq_war_prefight_champion'), 'war_prefight_attacker', ['war_id', 'battlegroup', 'champion_user_id'], unique=True)
    # ### end Alembic commands ###
