"""saga_per_season

Revision ID: 5e7dadb0ba03
Revises: 1f2745b9d082
Create Date: 2026-07-06 22:00:48.023824

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "5e7dadb0ba03"
down_revision: str | None = "1f2745b9d082"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "champion_saga_role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("season_id", sa.Uuid(), nullable=False),
        sa.Column("champion_id", sa.Uuid(), nullable=False),
        sa.Column("is_saga_attacker", sa.Boolean(), nullable=False),
        sa.Column("is_saga_defender", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["champion_id"], ["champion.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["season_id"], ["season.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "champion_id", name="uq_saga_season_champion"),
    )
    op.create_index(
        op.f("ix_champion_saga_role_champion_id"),
        "champion_saga_role",
        ["champion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_champion_saga_role_season_id"), "champion_saga_role", ["season_id"], unique=False
    )
    op.drop_column("champion", "is_saga_attacker")
    op.drop_column("champion", "is_saga_defender")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "champion",
        sa.Column(
            "is_saga_defender", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "champion",
        sa.Column(
            "is_saga_attacker", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_champion_saga_role_season_id"), table_name="champion_saga_role")
    op.drop_index(op.f("ix_champion_saga_role_champion_id"), table_name="champion_saga_role")
    op.drop_table("champion_saga_role")
    # ### end Alembic commands ###
