"""init

Revision ID: 6366528b2ae2
Revises: 87f64bfcb771
Create Date: 2026-04-19 03:19:56.267896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '6366528b2ae2'
down_revision: Union[str, None] = '87f64bfcb771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mastery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('max_value', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_account_mastery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_account_id', sa.Uuid(), nullable=False),
    sa.Column('mastery_id', sa.Uuid(), nullable=False),
    sa.Column('unlocked', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_account_id'], ['game_account.id'], ),
    sa.ForeignKeyConstraint(['mastery_id'], ['mastery.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_account_id', 'mastery_id', name='uq_account_mastery')
    )
    op.create_foreign_key(None, 'alliance', 'game_account', ['owner_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alliance', type_='foreignkey')
    op.drop_table('game_account_mastery')
    op.drop_table('mastery')
    # ### end Alembic commands ###
