"""freeze_only_attacker_rank_on_fight_record

Revision ID: 63f2212fe47b
Revises: bf49bae2d330
Create Date: 2026-09-15 01:00:31.715671

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63f2212fe47b"
down_revision: str | None = "bf49bae2d330"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "war_fight_record", sa.Column("war_defense_placement_id", sa.Uuid(), nullable=True)
    )
    bind = op.get_bind()
    mismatched = (
        bind.execute(
            sa.text(
                """
                SELECT r.id FROM war_fight_record r
                LEFT JOIN war_defense_placement p ON p.war_id = r.war_id
                    AND p.battlegroup = r.battlegroup AND p.node_number = r.node_number
                LEFT JOIN champion_user cu ON cu.id = p.attacker_champion_user_id
                WHERE p.id IS NULL OR cu.id IS NULL
                    OR cu.champion_id <> r.champion_id OR cu.game_account_id <> r.game_account_id
                """
            )
        )
        .scalars()
        .all()
    )
    if mismatched:
        message = f"{len(mismatched)} fight records match no placement: {mismatched}"
        raise RuntimeError(message)
    op.execute(
        """
        UPDATE war_fight_record r
        JOIN war_defense_placement p ON p.war_id = r.war_id
            AND p.battlegroup = r.battlegroup AND p.node_number = r.node_number
        SET r.war_defense_placement_id = p.id
        """
    )
    op.alter_column(
        "war_fight_record",
        "war_defense_placement_id",
        existing_type=sa.Uuid(),
        nullable=False,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("war_fight_synergy")
    op.drop_table("war_fight_prefight")
    op.create_unique_constraint(None, "war_fight_record", ["war_defense_placement_id"])
    op.drop_constraint(op.f("war_fight_record_ibfk_3"), "war_fight_record", type_="foreignkey")
    op.drop_constraint(op.f("war_fight_record_ibfk_1"), "war_fight_record", type_="foreignkey")
    op.drop_constraint(op.f("war_fight_record_ibfk_2"), "war_fight_record", type_="foreignkey")
    op.drop_constraint(op.f("war_fight_record_ibfk_6"), "war_fight_record", type_="foreignkey")
    op.drop_constraint(op.f("war_fight_record_ibfk_5"), "war_fight_record", type_="foreignkey")
    op.drop_constraint(op.f("war_fight_record_ibfk_4"), "war_fight_record", type_="foreignkey")
    op.create_foreign_key(
        None, "war_fight_record", "war_defense_placement", ["war_defense_placement_id"], ["id"]
    )
    op.drop_column("war_fight_record", "has_specials_boost")
    op.drop_column("war_fight_record", "defender_ascension")
    op.drop_column("war_fight_record", "champion_id")
    op.drop_column("war_fight_record", "defender_champion_id")
    op.drop_column("war_fight_record", "stars")
    op.drop_column("war_fight_record", "is_saga_attacker")
    op.drop_column("war_fight_record", "defender_stars")
    op.drop_column("war_fight_record", "has_power_boost")
    op.drop_column("war_fight_record", "ko_count")
    op.drop_column("war_fight_record", "is_planning_error")
    op.drop_column("war_fight_record", "defender_is_saga_defender")
    op.drop_column("war_fight_record", "season_id")
    op.drop_column("war_fight_record", "node_number")
    op.drop_column("war_fight_record", "defender_rank")
    op.drop_column("war_fight_record", "alliance_id")
    op.drop_column("war_fight_record", "tier")
    op.drop_column("war_fight_record", "war_id")
    op.drop_column("war_fight_record", "battlegroup")
    op.drop_column("war_fight_record", "war_boost")
    op.drop_column("war_fight_record", "game_account_id")
    op.drop_column("war_fight_record", "has_defense_boost")
    op.drop_column("war_fight_record", "assisted")
    # ### end Alembic commands ###


def downgrade() -> None:
    """The dropped copies cannot be rebuilt; restore a backup instead."""
    raise NotImplementedError
