"""init

Revision ID: 640fa6c40699
Revises: 2ffa199d1d75
Create Date: 2026-02-14 15:09:02.535934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '640fa6c40699'
down_revision: Union[str, None] = '2ffa199d1d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('discord_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_discord_id'), 'user', ['discord_id'], unique=True)
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_user_discord_id'), table_name='user')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'discord_id')
    # ### end Alembic commands ###
