"""add_war_boosts_to_defense_placement

Revision ID: 696816754471
Revises: 95c741c0039f
Create Date: 2026-09-10 09:16:58.949487

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "696816754471"
down_revision: str | None = "95c741c0039f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "war_defense_placement",
        sa.Column(
            "war_boost",
            sa.Enum("POWER_START", "INVULNERABILITY", "REGENERATION", name="warboost"),
            nullable=True,
        ),
    )
    # server_default backfills the existing rows; Alembic omits it, MariaDB would guess.
    op.add_column(
        "war_defense_placement",
        sa.Column("has_defense_boost", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "war_defense_placement",
        sa.Column("has_power_boost", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "war_defense_placement",
        sa.Column("has_specials_boost", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("war_defense_placement", "has_specials_boost")
    op.drop_column("war_defense_placement", "has_power_boost")
    op.drop_column("war_defense_placement", "has_defense_boost")
    op.drop_column("war_defense_placement", "war_boost")
    # ### end Alembic commands ###
