"""add_game_account_soft_delete

Revision ID: 71b1b4647961
Revises: 44ec4546df6d
Create Date: 2026-08-25 20:53:25.001401

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71b1b4647961"
down_revision: str | None = "44ec4546df6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game_account", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game_account", "deleted_at")
    # ### end Alembic commands ###
