"""uppercase_enum_member_names

Revision ID: 797935c1dcc1
Revises: 9f2902cba2db
Create Date: 2026-09-30 20:49:41.838664

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "797935c1dcc1"
down_revision: str | None = "9f2902cba2db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "defense_active_plan",
        "format",
        existing_type=mysql.ENUM("regular", "big_thing"),
        type_=sa.Enum("REGULAR", "BIG_THING", name="seasonformat"),
        existing_nullable=False,
    )
    op.alter_column(
        "defense_plan",
        "format",
        existing_type=mysql.ENUM("regular", "big_thing"),
        type_=sa.Enum("REGULAR", "BIG_THING", name="seasonformat"),
        existing_nullable=False,
    )
    op.alter_column(
        "defense_template",
        "format",
        existing_type=mysql.ENUM("regular", "big_thing"),
        type_=sa.Enum("REGULAR", "BIG_THING", name="seasonformat"),
        existing_nullable=False,
    )
    op.alter_column(
        "note_report",
        "status",
        existing_type=mysql.ENUM("pending", "resolved", "dismissed"),
        type_=sa.Enum("PENDING", "RESOLVED", "DISMISSED", name="notereportstatus"),
        existing_nullable=False,
    )
    op.alter_column(
        "season",
        "status",
        existing_type=mysql.ENUM("upcoming", "active", "ended"),
        type_=sa.Enum("UPCOMING", "ACTIVE", "ENDED", name="seasonstatus"),
        existing_nullable=False,
    )
    op.alter_column(
        "season",
        "format",
        existing_type=mysql.ENUM("regular", "big_thing"),
        type_=sa.Enum("REGULAR", "BIG_THING", name="seasonformat"),
        existing_nullable=False,
    )
    op.alter_column(
        "war",
        "status",
        existing_type=mysql.ENUM("active", "ended"),
        type_=sa.Enum("ACTIVE", "ENDED", name="warstatus"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "war",
        "status",
        existing_type=sa.Enum("ACTIVE", "ENDED", name="warstatus"),
        type_=mysql.ENUM("active", "ended"),
        existing_nullable=False,
    )
    op.alter_column(
        "season",
        "format",
        existing_type=sa.Enum("REGULAR", "BIG_THING", name="seasonformat"),
        type_=mysql.ENUM("regular", "big_thing"),
        existing_nullable=False,
    )
    op.alter_column(
        "season",
        "status",
        existing_type=sa.Enum("UPCOMING", "ACTIVE", "ENDED", name="seasonstatus"),
        type_=mysql.ENUM("upcoming", "active", "ended"),
        existing_nullable=False,
    )
    op.alter_column(
        "note_report",
        "status",
        existing_type=sa.Enum("PENDING", "RESOLVED", "DISMISSED", name="notereportstatus"),
        type_=mysql.ENUM("pending", "resolved", "dismissed"),
        existing_nullable=False,
    )
    op.alter_column(
        "defense_template",
        "format",
        existing_type=sa.Enum("REGULAR", "BIG_THING", name="seasonformat"),
        type_=mysql.ENUM("regular", "big_thing"),
        existing_nullable=False,
    )
    op.alter_column(
        "defense_plan",
        "format",
        existing_type=sa.Enum("REGULAR", "BIG_THING", name="seasonformat"),
        type_=mysql.ENUM("regular", "big_thing"),
        existing_nullable=False,
    )
    op.alter_column(
        "defense_active_plan",
        "format",
        existing_type=sa.Enum("REGULAR", "BIG_THING", name="seasonformat"),
        type_=mysql.ENUM("regular", "big_thing"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
