"""vision_sample_and_confirmed_status

Revision ID: 83a2e5379297
Revises: d9e0782238ed
Create Date: 2026-07-17 21:38:20.601087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "83a2e5379297"
down_revision: Union[str, None] = "d9e0782238ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vision_sample", sa.Column("import_id", sa.Uuid(), nullable=False))
    op.add_column("vision_sample", sa.Column("game_account_id", sa.Uuid(), nullable=False))
    op.add_column(
        "vision_sample", sa.Column("pred_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "vision_sample",
        sa.Column("dataset_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_vision_sample_game_account_id"), "vision_sample", ["game_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_vision_sample_import_id"), "vision_sample", ["import_id"], unique=False
    )
    op.drop_constraint(op.f("1"), "vision_sample", type_="foreignkey")
    op.drop_column("vision_sample", "job_id")
    op.drop_column("vision_sample", "prediction_json")
    # ### end Alembic commands ###
    # Manual addition — not autogenerated: MySQL native ENUM value additions are not
    # detected by Alembic's autogenerate diff, so VisionImportStatus.CONFIRMED must be
    # added to the DB enum by hand here (verified via SHOW CREATE TABLE that `status`
    # is a real ENUM('PENDING','RUNNING','DONE','FAILED'), not a varchar).
    op.alter_column(
        "vision_import",
        "status",
        existing_type=sa.Enum("PENDING", "RUNNING", "DONE", "FAILED", name="visionimportstatus"),
        type_=sa.Enum(
            "PENDING", "RUNNING", "DONE", "FAILED", "CONFIRMED", name="visionimportstatus"
        ),
        existing_nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column(
        "vision_import",
        "status",
        existing_type=sa.Enum(
            "PENDING", "RUNNING", "DONE", "FAILED", "CONFIRMED", name="visionimportstatus"
        ),
        type_=sa.Enum("PENDING", "RUNNING", "DONE", "FAILED", name="visionimportstatus"),
        existing_nullable=False,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vision_sample", sa.Column("prediction_json", mysql.VARCHAR(length=255), nullable=False)
    )
    op.add_column("vision_sample", sa.Column("job_id", mysql.CHAR(length=32), nullable=False))
    op.create_foreign_key(op.f("1"), "vision_sample", "vision_job", ["job_id"], ["id"])
    op.drop_index(op.f("ix_vision_sample_import_id"), table_name="vision_sample")
    op.drop_index(op.f("ix_vision_sample_game_account_id"), table_name="vision_sample")
    op.drop_column("vision_sample", "dataset_key")
    op.drop_column("vision_sample", "pred_json")
    op.drop_column("vision_sample", "game_account_id")
    op.drop_column("vision_sample", "import_id")
    # ### end Alembic commands ###
