"""add_snapshotted_at_to_war

Revision ID: 845077a610bf
Revises: d3389b4c1b38
Create Date: 2026-05-02 18:43:45.355716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "845077a610bf"
down_revision: Union[str, None] = "d3389b4c1b38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("war", sa.Column("snapshotted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("war", "snapshotted_at")
    # ### end Alembic commands ###
