"""add-big-thing-season

Revision ID: 8ab9a3f84ff8
Revises: 94d7d9280a40
Create Date: 2026-06-04 12:51:05.946853

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8ab9a3f84ff8"
down_revision: Union[str, None] = "94d7d9280a40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "season",
        sa.Column(
            "status", sa.Enum("upcoming", "active", "ended", name="seasonstatus"), nullable=False
        ),
    )
    op.add_column(
        "season",
        sa.Column("format", sa.Enum("regular", "big_thing", name="seasonformat"), nullable=False),
    )
    op.drop_column("season", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "season",
        sa.Column("is_active", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    )
    op.drop_column("season", "format")
    op.drop_column("season", "status")
    # ### end Alembic commands ###
