"""add_war_fight_record_import_table

Revision ID: 94d7d9280a40
Revises: a08a2f9b992c
Create Date: 2026-06-01 20:43:23.177069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "94d7d9280a40"
down_revision: Union[str, None] = "a08a2f9b992c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "war_fight_record_import",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alliance_id", sa.Uuid(), nullable=False),
        sa.Column("season_id", sa.Uuid(), nullable=True),
        sa.Column("node_number", sa.Integer(), nullable=False),
        sa.Column("champion_id", sa.Uuid(), nullable=False),
        sa.Column("defender_champion_id", sa.Uuid(), nullable=False),
        sa.Column("ko_count", sa.Integer(), nullable=False),
        sa.Column("imported_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alliance_id"],
            ["alliance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["champion_id"],
            ["champion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["defender_champion_id"],
            ["champion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["imported_by_id"],
            ["game_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("war_fight_record_import")
    # ### end Alembic commands ###
