"""init

Revision ID: 9566c7a3f06d
Revises: de011a409ae9
Create Date: 2026-02-25 22:23:04.288220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '9566c7a3f06d'
down_revision: Union[str, None] = 'de011a409ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requested_upgrade',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('champion_user_id', sa.Uuid(), nullable=False),
    sa.Column('requester_game_account_id', sa.Uuid(), nullable=False),
    sa.Column('requested_rarity', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['champion_user_id'], ['champion_user.id'], ),
    sa.ForeignKeyConstraint(['requester_game_account_id'], ['game_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requested_upgrade')
    # ### end Alembic commands ###
