"""add_opponent_deaths_to_war

Revision ID: 95c741c0039f
Revises: 1a0e2a6aa558
Create Date: 2026-09-09 22:32:20.398931

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95c741c0039f"
down_revision: str | None = "1a0e2a6aa558"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("war", sa.Column("opponent_deaths", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("war", "opponent_deaths")
    # ### end Alembic commands ###
