"""add_vision_infra

Revision ID: 98888a52433b
Revises: 8be10426cec1
Create Date: 2026-07-24 01:19:10.894462

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98888a52433b"
down_revision: str | None = "8be10426cec1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vision_sample",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column("game_account_id", sa.Uuid(), nullable=False),
        sa.Column("screen_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("dataset_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vision_sample_game_account_id"), "vision_sample", ["game_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_vision_sample_import_id"), "vision_sample", ["import_id"], unique=False
    )
    op.create_table(
        "vision_import",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "DONE",
                "FAILED",
                "CONFIRMED",
                "CANCELLED",
                name="visionimportstatus",
            ),
            nullable=False,
        ),
        sa.Column("screens_total", sa.Integer(), nullable=False),
        sa.Column("screens_done", sa.Integer(), nullable=False),
        sa.Column("share_dataset", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_account_id"],
            ["game_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vision_job",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "DONE", "FAILED", name="visionjobstatus"),
            nullable=False,
        ),
        sa.Column("object_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("result_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["vision_import.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vision_prediction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("champion_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("champion_class", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("signature", sa.Integer(), nullable=False),
        sa.Column("ascension", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("crop_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["vision_job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vision_prediction_candidate",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prediction_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["prediction_id"], ["vision_prediction.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vision_prediction_candidate_prediction_id"),
        "vision_prediction_candidate",
        ["prediction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_vision_prediction_candidate_prediction_id"),
        table_name="vision_prediction_candidate",
    )
    op.drop_table("vision_prediction_candidate")
    op.drop_table("vision_prediction")
    op.drop_table("vision_job")
    op.drop_table("vision_import")
    op.drop_index(op.f("ix_vision_sample_import_id"), table_name="vision_sample")
    op.drop_index(op.f("ix_vision_sample_game_account_id"), table_name="vision_sample")
    op.drop_table("vision_sample")
    # ### end Alembic commands ###
