"""defense_plans

Revision ID: 9f2902cba2db
Revises: 63f2212fe47b
Create Date: 2026-09-27 22:47:52.569703

"""

import uuid
from collections import defaultdict
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9f2902cba2db"
down_revision: str | None = "63f2212fe47b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Each Battlegroup keeps its layout: a regular plan with every row, a big_thing plan with
# nodes 1-10 whose players may sit over the cap (fixed by hand), both active.
_LEGACY_ROWS = sa.text(
    "SELECT dp.alliance_id, dp.battlegroup, dp.node_number, dp.champion_user_id,"
    " dp.placed_by_id, cu.champion_id"
    " FROM defense_placement dp JOIN champion_user cu ON cu.id = dp.champion_user_id"
)
_FORMAT_NODE_COUNT = (("regular", 50), ("big_thing", 10))


def _copy_placements_into_plans() -> None:
    bind = op.get_bind()
    by_bg: dict[tuple, list] = defaultdict(list)
    for row in bind.execute(_LEGACY_ROWS):
        by_bg[(row.alliance_id, row.battlegroup)].append(row)
    now = datetime.now(UTC)
    for (alliance_id, battlegroup), rows in by_bg.items():
        # Legacy data never enforced one champion per (alliance, battlegroup); keep only the lowest node.
        rows.sort(key=lambda r: r.node_number)
        for fmt, node_count in _FORMAT_NODE_COUNT:
            plan_id = uuid.uuid4().hex
            bind.execute(
                sa.text(
                    "INSERT INTO defense_plan (id, alliance_id, battlegroup, format, name,"
                    " source_template_id, created_at)"
                    " VALUES (:id, :alliance_id, :battlegroup, :format, 'Plan 1', NULL, :now)"
                ),
                {
                    "id": plan_id,
                    "alliance_id": alliance_id,
                    "battlegroup": battlegroup,
                    "format": fmt,
                    "now": now,
                },
            )
            seen_champion_ids: set = set()
            for row in rows:
                if row.champion_id in seen_champion_ids:
                    continue
                if row.node_number <= node_count:
                    seen_champion_ids.add(row.champion_id)
                    bind.execute(
                        sa.text(
                            "INSERT INTO defense_plan_node (id, plan_id, node_number, champion_id,"
                            " champion_user_id, placed_by_id)"
                            " VALUES (:id, :plan_id, :node, :champion_id, :cu_id, :placed_by_id)"
                        ),
                        {
                            "id": uuid.uuid4().hex,
                            "plan_id": plan_id,
                            "node": row.node_number,
                            "champion_id": row.champion_id,
                            "cu_id": row.champion_user_id,
                            "placed_by_id": row.placed_by_id,
                        },
                    )
            bind.execute(
                sa.text(
                    "INSERT INTO defense_active_plan (id, alliance_id, battlegroup, format, plan_id)"
                    " VALUES (:id, :alliance_id, :battlegroup, :format, :plan_id)"
                ),
                {
                    "id": uuid.uuid4().hex,
                    "alliance_id": alliance_id,
                    "battlegroup": battlegroup,
                    "format": fmt,
                    "plan_id": plan_id,
                },
            )


def _copy_active_regular_plans_back() -> None:
    op.get_bind().execute(
        sa.text(
            "INSERT INTO defense_placement (id, alliance_id, battlegroup, node_number,"
            " champion_user_id, game_account_id, placed_by_id, created_at)"
            " SELECT n.id, ap.alliance_id, ap.battlegroup, n.node_number, n.champion_user_id,"
            " cu.game_account_id, n.placed_by_id, p.created_at"
            " FROM defense_active_plan ap"
            " JOIN defense_plan p ON p.id = ap.plan_id"
            " JOIN defense_plan_node n ON n.plan_id = p.id"
            " JOIN champion_user cu ON cu.id = n.champion_user_id"
            " WHERE ap.format = 'regular'"
        )
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "defense_template",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("alliance_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("format", sa.Enum("regular", "big_thing", name="seasonformat"), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["alliance_id"],
            ["alliance.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alliance_id", "format", "name", name="uq_defense_template_name"),
    )
    op.create_table(
        "defense_plan",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("alliance_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("battlegroup", sa.Integer(), nullable=False),
        sa.Column("format", sa.Enum("regular", "big_thing", name="seasonformat"), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("source_template_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["alliance_id"],
            ["alliance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_template_id"], ["defense_template.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "alliance_id", "battlegroup", "format", "name", name="uq_defense_plan_name"
        ),
    )
    op.create_table(
        "defense_template_node",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("node_number", sa.Integer(), nullable=False),
        sa.Column("champion_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["champion_id"], ["champion.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["defense_template.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("template_id", "champion_id", name="uq_defense_template_champion"),
        sa.UniqueConstraint("template_id", "node_number", name="uq_defense_template_node"),
    )
    op.create_table(
        "defense_active_plan",
        sa.Column("alliance_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("battlegroup", sa.Integer(), nullable=False),
        sa.Column("format", sa.Enum("regular", "big_thing", name="seasonformat"), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alliance_id"],
            ["alliance.id"],
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["defense_plan.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alliance_id", "battlegroup", "format", name="uq_defense_active_plan"),
        sa.UniqueConstraint("plan_id"),
    )
    op.create_table(
        "defense_plan_node",
        sa.Column("placed_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("node_number", sa.Integer(), nullable=False),
        sa.Column("champion_id", sa.Uuid(), nullable=False),
        sa.Column("champion_user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["champion_id"], ["champion.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["champion_user_id"], ["champion_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["placed_by_id"],
            ["game_account.id"],
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["defense_plan.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "champion_id", name="uq_defense_plan_champion"),
        sa.UniqueConstraint("plan_id", "node_number", name="uq_defense_plan_node"),
    )
    # ### end Alembic commands ###
    _copy_placements_into_plans()
    # MariaDB reuses this index for the alliance_id FK, so dropping it needs the table gone too.
    op.drop_table("defense_placement")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "defense_placement",
        sa.Column("id", mysql.CHAR(length=32), nullable=False),
        sa.Column("alliance_id", mysql.CHAR(length=32), nullable=False),
        sa.Column(
            "battlegroup", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
        ),
        sa.Column(
            "node_number", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
        ),
        sa.Column("champion_user_id", mysql.CHAR(length=32), nullable=False),
        sa.Column("game_account_id", mysql.CHAR(length=32), nullable=False),
        sa.Column("placed_by_id", mysql.CHAR(length=32), nullable=True),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alliance_id"], ["alliance.id"], name=op.f("defense_placement_ibfk_1")
        ),
        sa.ForeignKeyConstraint(
            ["champion_user_id"], ["champion_user.id"], name=op.f("defense_placement_ibfk_2")
        ),
        sa.ForeignKeyConstraint(
            ["game_account_id"], ["game_account.id"], name=op.f("defense_placement_ibfk_3")
        ),
        sa.ForeignKeyConstraint(
            ["placed_by_id"], ["game_account.id"], name=op.f("defense_placement_ibfk_4")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_uca1400_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uq_defense_node"),
        "defense_placement",
        ["alliance_id", "battlegroup", "node_number"],
        unique=True,
    )
    # ### end Alembic commands ###
    _copy_active_regular_plans_back()
    op.drop_table("defense_plan_node")
    op.drop_table("defense_active_plan")
    op.drop_table("defense_template_node")
    op.drop_table("defense_plan")
    op.drop_table("defense_template")
