"""add_assisted_to_war_fight_record

Revision ID: a08a2f9b992c
Revises: b24d0bf5217d
Create Date: 2026-05-17 22:41:42.797154

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a08a2f9b992c"
down_revision: str | None = "b24d0bf5217d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "war_defense_placement", sa.Column("assist_champion_user_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        None, "war_defense_placement", "champion_user", ["assist_champion_user_id"], ["id"]
    )
    op.add_column("war_fight_record", sa.Column("assisted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("war_fight_record", "assisted")
    op.drop_constraint(None, "war_defense_placement", type_="foreignkey")
    op.drop_column("war_defense_placement", "assist_champion_user_id")
    # ### end Alembic commands ###
