"""init

Revision ID: a305c37823c5
Revises: 593c3eb26523
Create Date: 2026-04-05 03:33:43.216089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'a305c37823c5'
down_revision: Union[str, None] = '593c3eb26523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('champion', sa.Column('has_prefight', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('champion', 'has_prefight')
    # ### end Alembic commands ###
