"""b

Revision ID: a7643d6edb29
Revises: 59cb9b765093
Create Date: 2026-03-16 23:46:40.521662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'a7643d6edb29'
down_revision: Union[str, None] = '59cb9b765093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('war_defense_placement', sa.Column('attacker_champion_user_id', sa.Uuid(), nullable=True))
    op.add_column('war_defense_placement', sa.Column('ko_count', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'war_defense_placement', 'champion_user', ['attacker_champion_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'war_defense_placement', type_='foreignkey')
    op.drop_column('war_defense_placement', 'ko_count')
    op.drop_column('war_defense_placement', 'attacker_champion_user_id')
    # ### end Alembic commands ###
