"""add_app_config_and_season_big_thing

Revision ID: aaf911a7858b
Revises: a08a2f9b992c
Create Date: 2026-05-22 20:04:05.964687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "aaf911a7858b"
down_revision: Union[str, None] = "a08a2f9b992c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_config",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.execute("INSERT INTO app_config (`key`, `value`) VALUES ('current_season_id', 'null')")
    op.execute("INSERT INTO app_config (`key`, `value`) VALUES ('off_season_big_thing', 'false')")
    op.add_column("season", sa.Column("is_big_thing", sa.Boolean(), nullable=False))
    op.drop_column("season", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "season",
        sa.Column("is_active", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    )
    op.drop_column("season", "is_big_thing")
    op.drop_table("app_config")
    # ### end Alembic commands ###
