"""add_visitor

Revision ID: b24d0bf5217d
Revises: afb4119fc6b6
Create Date: 2026-05-08 02:41:12.748757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "b24d0bf5217d"
down_revision: Union[str, None] = "afb4119fc6b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alliance_visitor",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alliance_id", sa.Uuid(), nullable=False),
        sa.Column("game_account_id", sa.Uuid(), nullable=False),
        sa.Column("visited_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alliance_id"],
            ["alliance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_account_id"],
            ["game_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "alliance_invitation",
        sa.Column(
            "type",
            sa.Enum("MEMBER", "VISITOR", name="invitationtype"),
            nullable=False,
            server_default="MEMBER",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alliance_invitation", "type")
    op.drop_table("alliance_visitor")
    # ### end Alembic commands ###
