"""remove_avatar

Revision ID: b5c5e20d304c
Revises: d97fad54782b
Create Date: 2026-04-29 23:31:16.400451

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b5c5e20d304c"
down_revision: str | None = "d97fad54782b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "avatar_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("avatar_url", mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
