"""add_war_boosts_to_fight_record

Revision ID: bf49bae2d330
Revises: 696816754471
Create Date: 2026-09-10 09:43:05.648595

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf49bae2d330"
down_revision: str | None = "696816754471"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "war_fight_record",
        sa.Column(
            "war_boost",
            sa.Enum("POWER_START", "INVULNERABILITY", "REGENERATION", name="warboost"),
            nullable=True,
        ),
    )
    # Fights recorded before this migration kept no boost information: false, not unknown.
    op.add_column(
        "war_fight_record",
        sa.Column("has_defense_boost", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "war_fight_record",
        sa.Column("has_power_boost", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "war_fight_record",
        sa.Column("has_specials_boost", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("war_fight_record", "has_specials_boost")
    op.drop_column("war_fight_record", "has_power_boost")
    op.drop_column("war_fight_record", "has_defense_boost")
    op.drop_column("war_fight_record", "war_boost")
    # ### end Alembic commands ###
