"""add_vision_import_table

Revision ID: c0db5b555ef9
Revises: f1e8de91f46f
Create Date: 2026-07-14 17:12:28.891296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "c0db5b555ef9"
down_revision: Union[str, None] = "f1e8de91f46f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vision_import",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_account_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "DONE", "FAILED", name="visionimportstatus"),
            nullable=False,
        ),
        sa.Column("screens_total", sa.Integer(), nullable=False),
        sa.Column("screens_done", sa.Integer(), nullable=False),
        sa.Column("share_dataset", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_account_id"],
            ["game_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vision_job",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "DONE", "FAILED", name="visionjobstatus"),
            nullable=False,
        ),
        sa.Column("object_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("result_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["vision_import.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vision_prediction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("champion_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("signature", sa.Integer(), nullable=False),
        sa.Column("ascension", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("crop_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["vision_job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vision_sample",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("screen_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("prediction_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("truth_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["vision_job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vision_sample")
    op.drop_table("vision_prediction")
    op.drop_table("vision_job")
    op.drop_table("vision_import")
    # ### end Alembic commands ###
