"""init

Revision ID: cf569a429e39
Revises: e5fc895e30a6
Create Date: 2026-02-28 00:51:58.812837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'cf569a429e39'
down_revision: Union[str, None] = 'e5fc895e30a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('champion_user', sa.Column('is_preferred_attacker', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('champion_user', 'is_preferred_attacker')
    # ### end Alembic commands ###
