"""add_war_fight_record

Revision ID: d3389b4c1b38
Revises: 0cc33c59d17e
Create Date: 2026-05-02 02:51:25.075653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'd3389b4c1b38'
down_revision: Union[str, None] = '0cc33c59d17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('war_fight_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('war_id', sa.Uuid(), nullable=False),
    sa.Column('alliance_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=True),
    sa.Column('game_account_id', sa.Uuid(), nullable=False),
    sa.Column('battlegroup', sa.Integer(), nullable=False),
    sa.Column('node_number', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Uuid(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('ascension', sa.Integer(), nullable=False),
    sa.Column('is_saga_attacker', sa.Boolean(), nullable=False),
    sa.Column('defender_champion_id', sa.Uuid(), nullable=False),
    sa.Column('defender_stars', sa.Integer(), nullable=False),
    sa.Column('defender_rank', sa.Integer(), nullable=False),
    sa.Column('defender_ascension', sa.Integer(), nullable=False),
    sa.Column('defender_is_saga_defender', sa.Boolean(), nullable=False),
    sa.Column('ko_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.id'], ),
    sa.ForeignKeyConstraint(['champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['defender_champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['game_account_id'], ['game_account.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('war_fight_prefight',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('war_fight_record_id', sa.Uuid(), nullable=False),
    sa.Column('champion_id', sa.Uuid(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('ascension', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['war_fight_record_id'], ['war_fight_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('war_fight_synergy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('war_fight_record_id', sa.Uuid(), nullable=False),
    sa.Column('champion_id', sa.Uuid(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('ascension', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['war_fight_record_id'], ['war_fight_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('war_fight_synergy')
    op.drop_table('war_fight_prefight')
    op.drop_table('war_fight_record')
    # ### end Alembic commands ###
