"""add_google_login

Revision ID: d97fad54782b
Revises: 178b878847d9
Create Date: 2026-04-29 22:38:44.620325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d97fad54782b"
down_revision: Union[str, None] = "178b878847d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("google_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column("user", "discord_id", existing_type=mysql.VARCHAR(length=255), nullable=True)
    op.create_index(op.f("ix_user_google_id"), "user", ["google_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_google_id"), table_name="user")
    op.alter_column("user", "discord_id", existing_type=mysql.VARCHAR(length=255), nullable=False)
    op.drop_column("user", "google_id")
    # ### end Alembic commands ###
