"""init

Revision ID: de011a409ae9
Revises: f8c1cc6bdc47
Create Date: 2026-02-23 18:48:30.897630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de011a409ae9'
down_revision: Union[str, None] = 'f8c1cc6bdc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('champion_user', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('champion_user', sa.Column('level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
