"""add_prefights

Revision ID: e2baeab914ab
Revises: f4eb8c81064b
Create Date: 2026-04-05 04:11:17.067179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'e2baeab914ab'
down_revision: Union[str, None] = 'f4eb8c81064b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('war_prefight_attacker',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('war_id', sa.Uuid(), nullable=False),
    sa.Column('battlegroup', sa.Integer(), nullable=False),
    sa.Column('game_account_id', sa.Uuid(), nullable=False),
    sa.Column('champion_user_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['champion_user_id'], ['champion_user.id'], ),
    sa.ForeignKeyConstraint(['game_account_id'], ['game_account.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('war_id', 'battlegroup', 'champion_user_id', 'target_node_number', name='uq_war_prefight_champion_node')
    )
    op.add_column('champion', sa.Column('has_prefight', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('champion', 'has_prefight')
    op.drop_table('war_prefight_attacker')
    # ### end Alembic commands ###
