"""add defense

Revision ID: e5fc895e30a6
Revises: 9566c7a3f06d
Create Date: 2026-02-27 22:14:27.839537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'e5fc895e30a6'
down_revision: Union[str, None] = '9566c7a3f06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defense_placement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alliance_id', sa.Uuid(), nullable=False),
    sa.Column('battlegroup', sa.Integer(), nullable=False),
    sa.Column('node_number', sa.Integer(), nullable=False),
    sa.Column('champion_user_id', sa.Uuid(), nullable=False),
    sa.Column('game_account_id', sa.Uuid(), nullable=False),
    sa.Column('placed_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.id'], ),
    sa.ForeignKeyConstraint(['champion_user_id'], ['champion_user.id'], ),
    sa.ForeignKeyConstraint(['game_account_id'], ['game_account.id'], ),
    sa.ForeignKeyConstraint(['placed_by_id'], ['game_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alliance_id', 'battlegroup', 'node_number', name='uq_defense_node')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defense_placement')
    # ### end Alembic commands ###
