"""add_matchup_rating_and_synergy

Revision ID: f1e8de91f46f
Revises: 5e7dadb0ba03
Create Date: 2026-07-09 15:36:22.569218

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1e8de91f46f"
down_revision: str | None = "5e7dadb0ba03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matchup_rating",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("alliance_id", sa.Uuid(), nullable=False),
        sa.Column("champion_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target_type", sa.Enum("DEFENDER", "NODE", name="matchuptargettype"), nullable=False
        ),
        sa.Column("defender_champion_id", sa.Uuid(), nullable=True),
        sa.Column("node_number", sa.Integer(), nullable=True),
        sa.Column("target_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "verdict", sa.Enum("DISCOURAGED", "OK", "GOOD", name="matchupverdict"), nullable=False
        ),
        sa.Column("prefight_champion_id", sa.Uuid(), nullable=True),
        sa.Column("season_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_game_account_id", sa.Uuid(), nullable=False),
        sa.Column("updated_by_game_account_id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(target_type = 'DEFENDER' AND defender_champion_id IS NOT NULL AND node_number IS NULL) OR (target_type = 'NODE' AND node_number IS NOT NULL AND defender_champion_id IS NULL)",
            name="ck_matchup_rating_single_target",
        ),
        sa.ForeignKeyConstraint(
            ["alliance_id"],
            ["alliance.id"],
        ),
        sa.ForeignKeyConstraint(
            ["champion_id"],
            ["champion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_game_account_id"],
            ["game_account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["defender_champion_id"],
            ["champion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prefight_champion_id"],
            ["champion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_game_account_id"],
            ["game_account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "alliance_id", "champion_id", "target_key", name="uq_matchup_rating_target"
        ),
    )
    op.create_table(
        "matchup_synergy",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("matchup_rating_id", sa.Uuid(), nullable=False),
        sa.Column("champion_id", sa.Uuid(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["champion_id"],
            ["champion.id"],
        ),
        sa.ForeignKeyConstraint(["matchup_rating_id"], ["matchup_rating.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("matchup_rating_id", "champion_id", name="uq_matchup_synergy_champion"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matchup_synergy")
    op.drop_table("matchup_rating")
    # ### end Alembic commands ###
