"""add bans

Revision ID: f4eb8c81064b
Revises: 08e07b56f4a1
Create Date: 2026-04-04 00:11:13.917988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'f4eb8c81064b'
down_revision: Union[str, None] = '08e07b56f4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('war_ban',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('war_id', sa.Uuid(), nullable=False),
    sa.Column('champion_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('war_id', 'champion_id', name='uq_war_ban_champion')
    )
    op.create_index(op.f('ix_war_ban_war_id'), 'war_ban', ['war_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_war_ban_war_id'), table_name='war_ban')
    op.drop_table('war_ban')
    # ### end Alembic commands ###
