"""init

Revision ID: f8c1cc6bdc47
Revises: 2d239a911782
Create Date: 2026-02-22 21:50:38.209347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'f8c1cc6bdc47'
down_revision: Union[str, None] = '2d239a911782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'alliance', 'game_account', ['owner_id'], ['id'], use_alter=True)
    op.add_column('champion', sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.create_unique_constraint(None, 'champion', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'champion', type_='unique')
    op.drop_column('champion', 'alias')
    op.drop_constraint(None, 'alliance', type_='foreignkey')
    # ### end Alembic commands ###
