"""hash_email

Revision ID: f9e052192b3a
Revises: a7643d6edb29
Create Date: 2026-03-27 10:51:19.860452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f9e052192b3a'
down_revision: Union[str, None] = 'a7643d6edb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('email_hash_version', sa.Integer(), nullable=False))
    op.drop_index(op.f('email'), table_name='user')
    op.create_unique_constraint(None, 'user', ['email_hash'])
    op.drop_column('user', 'email')
    op.alter_column('war', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('active', 'ended', name='warstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('war', 'status',
               existing_type=sa.Enum('active', 'ended', name='warstatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index(op.f('email'), 'user', ['email'], unique=True)
    op.drop_column('user', 'email_hash_version')
    op.drop_column('user', 'email_hash')
    # ### end Alembic commands ###
